# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9a45d7d5b4b71b54680b7ba854ca4e923b2d24b9b5fd91d9dd3369751ca0fa8a0c78b3055a64b9d576b692a70d731b1f3b89ca2ee9dc902186a20bda14f75ec

test:
  secret_key_base: e3f789631c529662e82796d41a6fb4436b64789351c7e12bf2aef47c90bb59104b0f411f9f2b3ae4e564af7618d638a4f2f372321a44f63c525585d073e94157

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
